name: gowol
version: "0.1.2+git"
icon: gowol.png
license: MIT
summary: A quick and easy way to wake up a computer via a snap
description: |
  GoWoL lets you send a Wake-on-LAN request from anywhere you can access the server running this snap.

grade: stable
confinement: strict

base: core

architectures:
  - build-on: arm64
  - build-on: amd64
  - build-on: armhf
  - build-on: s390x
  - build-on: ppc64el

apps:
  server:
    command: $SNAP/bin/wol
    plugs:
      - network
      - network-bind

parts:
  wol:
    plugin: go
    source-type: git
    source: ../..
    build-snaps:
      - go/latest/stable
