name: gowol
version: 0.1+git
summary: A quick and easy way to wake up a computer via a snap
description: |
  GoWoL lets you send a WoL request from outside a network.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

base: core18

parts:
  wol:
    plugin: go
    # go-packages:
    #   - github.com/thethorne48/wol/packet
    go-importpath: github.com/thethorne48/wol
    source: src
    source-type: local
    # source-branch: dev
    
apps:
  goWol:
    command: bin/wol
