name: gowol
version: 0.1+git
icon: gowol.png
summary: A quick and easy way to wake up a computer via a snap
description: |
  GoWoL lets you send a WoL request from outside a network.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

base: core18

parts:
  wol:
    plugin: go
    go-importpath: github.com/thethorne48/wol
    source: .
    source-type: git
    
apps:
  goWol:
    command: bin/wol
