name: gowol
version: 0.1.1+git
icon: gowol.png
summary: A quick and easy way to wake up a computer via a snap
description: |
  GoWoL lets you send a WoL request from outside a network.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

base: core22

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  - build-on: s390x
  - build-on: ppc64el

parts:
  wol:
    plugin: go
    source-type: git
    source: https://github.com/thethorne48/wol
    build-snaps:
      - go

apps:
  goWol:
    command: bin/gowol
    plugs:
      - network
      - network-bind
